// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXIjgZIVLlKIFohBltSIkmVmgIBm2N9J4',
    appId: '1:122651634072:web:a5e25a0de193a46309a3ed',
    messagingSenderId: '122651634072',
    projectId: 'newlj-documents',
    authDomain: 'newlj-documents.firebaseapp.com',
    storageBucket: 'newlj-documents.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr4-vntZ-WWqqmRq9BhebDmQfhSAuGrks',
    appId: '1:122651634072:android:c023bbeaf7fca04609a3ed',
    messagingSenderId: '122651634072',
    projectId: 'newlj-documents',
    storageBucket: 'newlj-documents.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApYr8gEFxZmRFQPZRsKX58SSC2pVCr2-Y',
    appId: '1:122651634072:ios:134a32b77c715e7b09a3ed',
    messagingSenderId: '122651634072',
    projectId: 'newlj-documents',
    storageBucket: 'newlj-documents.appspot.com',
    iosBundleId: 'com.example.newLj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApYr8gEFxZmRFQPZRsKX58SSC2pVCr2-Y',
    appId: '1:122651634072:ios:5d456669508fd6d109a3ed',
    messagingSenderId: '122651634072',
    projectId: 'newlj-documents',
    storageBucket: 'newlj-documents.appspot.com',
    iosBundleId: 'com.example.newLj.RunnerTests',
  );
}
